<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.12.0
 * FormDin Version: 4.24.0
 * 
 * System za created in: 2024-05-22 18:08:25
 */

if ( !function_exists( 'af7605_api_autoload') ) {
    function af7605_api_autoload( $class_name )
    {
        $class_name = str_replace('\\',DS,$class_name);
        $path = __DIR__.DS.$class_name.'.class.php';
        if (file_exists($path)){
            require_once $path;
        } else {
            return false;
        }
    }
    spl_autoload_register('af7605_api_autoload');
}