<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.12.0
 * FormDin Version: 4.24.0
 * 
 * System za created in: 2024-05-22 18:08:29
 */

if (! defined ( 'DS' )) {
    define ( 'DS', DIRECTORY_SEPARATOR );
}
$current_dirApi = dirname ( __FILE__ );

require $current_dirApi.DS.'..'.DS.'vendor/autoload.php';
require_once $current_dirApi.DS.'autoload_af7605_api.php';

//REMOVER SE ESTIVER USANDO FormDin5
require_once $current_dirApi.DS.'helpers'.DS.'ArrayHelper.class.php';
require_once $current_dirApi.DS.'helpers'.DS.'CountHelper.class.php';
require_once $current_dirApi.DS.'helpers'.DS.'ServerHelper.class.php';

//--------------------------------------------------------------------------------
require_once $current_dirApi.DS.'env.php';
require_once $current_dirApi.DS.'routes.php';